# Generated by Django 5.2.9 on 2025-12-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_notified_alter_category_id_alter_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_link_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
